name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: sail
          aws-secret-access-key: password
          aws-region: us-west-2

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name MyDemoApplication \
            --deployment-group-name MyDemoDeploymentGroup \
            --s3-location bucket=dwb-dev-testing-env,key=my-app.zip,bundleType=zip
